name: Deploy

on: push

env:
  TF_VERSION: 1.5.1

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Cache Tarraform
        id: cache-terraform
        uses: actions/cache@v3
        env:
          cache-name: cache-terraform
        with:
          path: .terraform
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-terraform.outputs.cache-hit != 'true' }}
        name: No Cache
        run: echo "No Cache"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan