name: Deploy

on: push

env:
  TF_VERSION: 1.5.1
  TF_DIR: '.terraform.d'

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Cache Terraform directories
        id: cache-terraform
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.TF_DIR }}/plugin-cache
            ${{ env.TF_DIR }}/checkpoint_cache
            ${{ env.TF_DIR }}/checkpoint_signature
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Create directories if not exist
        run: |
          mkdir -p "${{ env.TF_DIR }}/plugin-cache"
          export TF_PLUGIN_CACHE_DIR="${{ env.TF_DIR }}/plugin-cache"
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
      - name: Debug
        run: ls $HOME/.terraform.d
